name: Bug Report
description: If you encounter a bug whilst using the app. Please use this template to help improve the app.
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    id: message
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
          required: true
        - label: I am sure that my bug has nothing to with third party extensions.
          required: true          
        - label: I have read the [troubleshooting FAQs](https://paperback.moe/faq/troubleshooting/) and looked trough the \#help-desk channel on the [official Discord](https://discord.com/invite/Paperback), but none solved my issue.
          required: true
        - label: I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a bug report that matches the one I want to file, without success.
          required: true
  - type: dropdown
    id: device-types
    attributes:
      label: What type of Apple device have you encountered the bug with?
      multiple: true
      options:
        - All device types
        - iPhone
        - iPad
        - Mac computer
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: What operating system version are you using? Go to 'Settings' > 'General' > 'About' for iOS and iPadOS devices; click 'the Apple logo in the top-left corner' > 'About This Mac' for macOS devices.
      placeholder: "e.g. iOS 16.6, iPadOS 16.6 or macOS Ventura 13.5"
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of Paperback are you using? You can find this info at the bottom of the settings page from within the app.
      placeholder: "e.g. 0.8.6-r2 or 0.7-r47 etc"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug that you encountered. Tell us what you expected to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: bug-replication
    attributes:
      label: Steps to Reproduce
      description: How did you produce this bug, tell us how you did it so we can reproduce it ourselves.
      placeholder: 1. ...
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Anything Else?
      description: |
        Links? References? Anything that will give us more context about the bug you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Images, links, logs, ...
    validations:
      required: false
